# Generated by Django 4.2.3 on 2023-08-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_remove_documental_deseado_remove_pelicula_deseado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documental',
            name='plataforma',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='plataforma',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serie',
            name='plataforma',
            field=models.CharField(max_length=100),
        ),
    ]
